### PR TITLE
Add support FRACTION on mainnet

### PR DESCRIPTION
**Pull request by ArjunBhuptani**

### CODE REVIEW

**Review by LayneHaber — CHANGES_REQUESTED** [review]
need link of changes added to chainlist repo before we can approve + merge

**Comment by LayneHaber** [comment]
need FRACTION to enlist connext as minters before we can submit any onchain txs

**Comment by just-a-node** [comment]
Close in favor of #4958

**Review by just-a-node — APPROVED** [review]

**Review by just-a-node — APPROVED** [review]

**Review by just-a-node — APPROVED** [review]

**Review by liu-zhipeng — APPROVED** [review]

**Review by sanchaymittal — APPROVED** [review]

**Comment by just-a-node** [comment]
> need link of changes added to chainlist repo before we can approve + merge

https://github.com/connext/chaindata/pull/105

**Pull request merged**
