### PR TITLE
Better cache cleanup on sequencer-publisher

### PR DESCRIPTION
**Pull request by wanglonghong**
## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## Related Issue(s)

Fixes

### CODE REVIEW

**Review by rhlsthrm — APPROVED** [review]
Definitely need this.

**Comment by rhlsthrm** [comment]
However this would not cause out of mem errors since the cache is a separate process.

**Comment by wanglonghong** [comment]
> However this would not cause out of mem errors since the cache is a separate process.

maybe, by the way, would you post the possible causes for out of mem errors?

**Comment by rhlsthrm** [comment]
> > However this would not cause out of mem errors since the cache is a separate process.
> 
> maybe, by the way, would you post the possible causes for out of mem errors?

We don't know, this is still under investigation. But it is something within the app, not the external cache.

**Pull request merged**
