### PR TITLE
feat: added readme for chain-abstraction

### PR DESCRIPTION
**Pull request by prathmeshkhandelwal1**
#4074 Fixed

### CODE REVIEW

**Comment by sanchaymittal** [comment]
I think we should directly add it to docs, instead of ReadMe. Better to maintain and keep docs to latest.
cc: @rhlsthrm

**Comment by rhlsthrm** [comment]
Agree with @sanchaymittal , the readme should contain instructions for running code locally, testing, etc. And then point to the docs for usage examples.

**Comment by prathmeshkhandelwal1** [comment]
> Agree with @sanchaymittal , the readme should contain instructions for running code locally, testing, etc. And then point to the docs for usage examples.

Sure, Changing it accordingly

**Comment by prathmeshkhandelwal1** [comment]
Suggested changes added @rhlsthrm 
cc: @alexwhte

**Review by rhlsthrm — APPROVED** [review]

**Pull request merged**
