### PR TITLE
add BTRST token to allowlisting scripts

### PR DESCRIPTION
**Pull request by multiart**
## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## Related Issue(s)

Fixes 

## Related pull request(s)

Chaindata: https://github.com/connext/chaindata/pull/81

### CODE REVIEW

**Comment by prathmeshkhandelwal1** [comment]
Hey @multiart, thank you for opening this PR! 😄

I have one strong suggestion to add: your canonical contract on Goerli is not verified. We highly recommend you to verify it, as it will help ensure that the related symbols, decimals, and other information in this PR are correct. Once the details are added, they cannot be changed in this case.

You can verify the contract at this link:
[Goerli Contract Verification](https://goerli.etherscan.io/address/0x39e09359F5a7396937504Eb2766722e2bf4650e8#code)

Let's make sure everything is accurate before proceeding further. Thanks! 🙏

**Review by prathmeshkhandelwal1 — CHANGES_REQUESTED** [review]
Hey @multiart, thank you for opening this PR! 😄

I have one strong suggestion to add: your canonical contract on Goerli is not verified. We highly recommend you to verify it, as it will help ensure that the related symbols, decimals, and other information in this PR are correct. Once the details are added, they cannot be changed in this case.

You can verify the contract at this link:
[Goerli Contract Verification](https://goerli.etherscan.io/address/0x39e09359F5a7396937504Eb2766722e2bf4650e8#code)

Let's make sure everything is accurate before proceeding further. Thanks! 🙏

**Comment by multiart** [comment]
> Hey @multiart, thank you for opening this PR! smile
> 
> I have one strong suggestion to add: your canonical contract on Goerli is not verified. We highly recommend you to verify it, as it will help ensure that the related symbols, decimals, and other information in this PR are correct. Once the details are added, they cannot be changed in this case.
> 
> You can verify the contract at this link: [Goerli Contract Verification](https://goerli.etherscan.io/address/0x39e09359F5a7396937504Eb2766722e2bf4650e8#code)
> 
> Let's make sure everything is accurate before proceeding further. Thanks! pray

Hi @prathmeshkhandelwal1.
Thank you for the info, the contract is already verified :)

**Comment by prathmeshkhandelwal1** [comment]
Thanks for adding verification, we will move forward asap with whitelisting process.

**Review by just-a-node — APPROVED** [review]

**Comment by prathmeshkhandelwal1** [comment]
Hey @multiart , We have approved the PR, but it can not pass untill it goes through ci/cd flow. The PR is having issues in validating commits, you might need to add one more commit with proper message.

**Comment by prathmeshkhandelwal1** [comment]
Also it would be great if you can mint some test BTRST tokens on this address `0x7b88c13D5A56549B2F09BB7D8300e256056fdD85`, will help us with final test in bridge UI

**Comment by prathmeshkhandelwal1** [comment]
Hey @multiart , Asset is verified now. 🎉 .
You can check it here. https://goerli.etherscan.io/tx/0x67520a6c94a9ab3c5ba2a4833b94b6996119381474ff09767ff2f2eb83d284ec#eventlog

To see BTRST in action in out bridge UI.
You might wanna follow these mentioned steps:
https://docs.connext.network/usecases/xerc20/setup-guide#connextscan-and-bridge-support

**Comment by just-a-node** [comment]
@multiart Congrats! BTRST is crosschain on testnet. We've seeded a small amount of BTRST router liquidity on Goerli and Mumbai to facilitate fast transfers. 

e.g. https://testnet.connextscan.io/tx/0x2aa26b7892260650eed39726aaac405a10df178dfafd0e3b2e7e63baea633b11

**Comment by just-a-node** [comment]
@multiart Do you have a telegram handle we can contact you at about next steps for taking this to mainnet?

**Comment by multiart** [comment]
> @multiart Do you have a telegram handle we can contact you at about next steps for taking this to mainnet?

My tg account is @maciejbienia .

**Pull request merged**
