### PR TITLE
3692 update vendor sdks

### LINKED ISSUE #3692: Update vendor SDKs
## Background

We use vendor SDKs in lighthouse, carto, etc from Arbitrum, Optimism, Polygon, etc. We are outdated on some of them and need to update our usage to get to the latest version.

## Definition Of Done

All versions to vendor SDKs are updated.

## Tasks

- [x] Find out which SDKs are used.
- [x] Update SDKs.
- [ ] Verify everything still works.

### PR DESCRIPTION
**Pull request by LayneHaber**
## Description

Fixes #3692 

## Type of change

- [x] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

- Upgrades arbitrum
- Upgrades optimism
- Upgrades zksync
- Ensures polygon, gnosis are updated if needed

## Related Issue(s)

Fixes #3692

### CODE REVIEW

**Comment by LayneHaber** [comment]
need to test on mainnets and testiest

**Review by rhlsthrm — APPROVED** [review]

**Comment by rhlsthrm** [comment]
@LayneHaber are we ever going to merge this lol.

**Comment by rhlsthrm** [comment]
@LayneHaber

**Review by preethamr — APPROVED** [review]
LGTM

**Review by preethamr — DISMISSED** [review]

**Review by just-a-node — DISMISSED** [review]

**Review by wanglonghong — APPROVED** [review]

**Review by liu-zhipeng — APPROVED** [review]

**Review by wanglonghong — DISMISSED** [review]

**Review by sanchaymittal — APPROVED** [review]

**Review by rhlsthrm — DISMISSED** [review]

**Review by preethamr — APPROVED** [review]
LGTM

**Review by rhlsthrm — APPROVED** [review]

**Review by just-a-node — APPROVED** [review]

**Pull request merged**
